### ISSUE TITLE
Add User Model , API and wallet

### ISSUE THREAD

**Issue by anacromaniac** [ByPassaRe/Pick-A-Park-RestfulApi#5]
**As a Driver**,

**I want to** add money to my account's wallet
**so that** I can pay for the parking

Tasks:
- [x] Create user model @corradopetrelli 
- [x] Attach Wallet to user
- [x] Create User APIs (CRUD) @corradopetrelli @an4cr0n

**Comment by tananai** [comment]
Useful:
- https://github.com/dhaspden/nestjs-stripe
- https://github.com/nestjsx/nestjs-braintree
